### PR TITLE
Implement Frame and FrameObject classes

### PR DESCRIPTION
**Pull request by bhokansonfasig**
Frame handles a map of strings to FrameObject shared pointers. Implements add, get, remove, and keys functions which do what you would expect to the frame. FrameObject is a nearly empty base class for particles, etc. The only thing to extend in child classes is pretty_name_, which is just what is used to distinguish what the class is without relying on the class name in the code.

### CODE REVIEW

**Comment by bhokansonfasig** [comment]
I didn't write any custom constructors or destructors. Are they needed?

**Comment by dsschult** [comment]
Might want to put the method implementations into a .cpp file, instead of in the header.

**Comment by bhokansonfasig** [comment]
Oh yeah. Anything that's not one line pretty much, right?
And .cpp file goes in src directory?

**Comment by dsschult** [comment]
Generally, if the function is not inlined, it should be in cpp.  One-line functions are usually inlined, thus that rule.

And yes, cpp goes in src.

**Pull request merged**
